### ISSUE TITLE
Alignment error

### ISSUE THREAD

**Issue by classner** [yifita/pytorch_points#2]
Hi!

I'm getting the following errors when compiling `pytorch_points`:

```
pytorch_points/_ext/nmdistance_cuda.cu(9): error: specified alignment (4) is different from alignment (8) specified on a previous declaration
          detected during instantiation of "void NmDistanceKernel(int, int, int, const scalar_t *, int, const scalar_t *, scalar_t *, int *) [with scalar_t=float]" 
(163): here

pytorch_points/_ext/nmdistance_cuda.cu(9): error: specified alignment (2) is different from alignment (8) specified on a previous declaration
          detected during instantiation of "void NmDistanceKernel(int, int, int, const scalar_t *, int, const scalar_t *, scalar_t *, int *) [with scalar_t=c10::Half]" 
(163): here
```

Any ideas on how to fix them?

**Comment by yifita** [comment]
Hi, It's related to template + cuda dynamic memory allocation.
But instead of being a warning for me, it somehow became an error for you. Are you using cuda10? 
This answer might be helpful for you https://stackoverflow.com/a/49224531/1326770

**Comment by classner** [comment]
I'm using the clang compiler, so maybe that's why it's an error for me. I'm using CUDA 10.2.

**Comment by yifita** [comment]
i think you can install gcc on mac. i'll close the issue for now.
